export const RECOVERY_IDENTIFIER_COOKIE = 'RECOVERY_IDENTIFIER'
export const RECOVERY_RESET_TOKEN_COOKIE = 'RECOVERY_RESET_TOKEN'

export const RECOVERY_IDENTIFIER_MAX_AGE_SECONDS = 15 * 60
export const RECOVERY_RESET_TOKEN_MAX_AGE_SECONDS = 10 * 60
